### ISSUE TITLE
DOM-based cross-site scripting

### ISSUE THREAD

**Issue by Derek000** [kumpul/wordpress-the7-child-theme#3]
Hi,

I reviewing a site using this theme and have detected a possible DOM-based cross-site scripting issue with /dt-the7-child/js/ucasa.js 

Specifically relating to the the data being read from location.href and passed to $(), via the following statement:       var target = $('#'+location.href.split("#")[1]);

Has this observation been discussed or the code been reviewed in the past?

**Comment by DennisAlund** [comment]
Hi, sorry for a very late reply. This theme is not maintained by [@kumpul](https://github.com/kumpul) as it was purchased and downloaded from a marketplace. It was just placed in our repository for ease of maintenance as it is under GPL license anyway.

We are no longer using WP for our website and I'll probably just archive this repository. 

Please contact the theme maintainers directly. I think this is the website for the theme: https://the7.io/

We're developing our own FOSS CMS for givnig true control and power to selfhost without dependencies on VPS providers or paid SSL certificates. Please feel free to check out or contribute to [@oddbit/tanam](https://github.com/oddbit/tanam/)
